---
title: "Exploratory Analysis"
output: github_document
---

```{r}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 6,
  out.width = "90%"
  )

theme_set(theme_minimal() + theme(legend.position = "bottom"))
          
options(
    ggplot2.continuous.colour = "viridis",
    ggplot2.continuous.fill = "viridis"
    )

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_color_viridis_d
```


## Load the weather data 

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
  month = lubridate::floor_date(date,"month")) %>% 
  select(name, id, everything())

weather_df
```


## `group_by`

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  ungroup(month)

```


## Counting things

Count name/month observations 

```{r}
weather_df %>% 
  group_by(name, month) %>%
  summarize(n_obs = n())
```

we can use `count()`

```{r}
weather_df %>% 
  count(name, month, name = "n_obs") 
```

**NEVER** use vase R's `table`

```{r, eval = FALSE}
weather_df %>% 
  pull(month) %>% 
  table()
```

Other helpful counters 

```{r}
weather_df %>% 
  group_by(month) %>%
  summarize(
    n_obs = n(),
    n_days = n_distinct(date))
```

## A digression on 2x2 tables 

```{r}
weather_df %>% 
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ ""
  )) %>% 
  filter(name != "Waikiki_HA") %>%  
  group_by(name, cold) %>% 
  summarize(count = n())
```


```{r}
weather_df %>% 
  mutate(cold = case_when(
    tmax <  5 ~ "cold",
    tmax >= 5 ~ "not_cold",
    TRUE     ~ ""
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  janitor::tabyl(name, cold)
```

## General summaries 

You can do lots of summaries.. 
```{r}
weather_df %>%
  group_by(month) %>%
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    mean_prec = mean(prcp, na.rm = TRUE),
    median_tmax = median(tmax, na.rm = TRUE),
    sd_tmax = sd(tmax))
```


```{r}
weather_df %>%
  group_by(month, name) %>%
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    mean_prec = mean(prcp, na.rm = TRUE),
    median_tmax = median(tmax, na.rm = TRUE),
    sd_tmax = sd(tmax)
    ) %>% 
   ggplot(aes(x = month, y = mean_tmax, color = name)) + 
    geom_point() + 
    geom_line()
```


Suppose you want to summarize many columns. 

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(across(prcp:tmin, mean))
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>% 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax) %>% 
  knitr::kable(digits = 1)
```











